### ISSUE TITLE
عدم اتصال

### ISSUE THREAD

**Issue by aghajani82** [lowercase78/V2RayN-PRO#1]
باسلام و خسته نباشید خدمت دوستان
مشکلی داشتم 
البته الان چند وقته که آپدیت های جدید نرم افزار برای من کار نمیکنه
ورژنی که در حال حاضر دارم باهاش کار میکنم 6.37 هستش
نمیدونم شاید برای اینه که ویندوزم 7 هستش
البته ویندوز 7 64 بیتی ه
برنامه رو طبق آموزش صفحه اصلی قرار دادم
برنامه رو یک بار کامل بستم و دوباره اجرا کردم. ولی خب متاسفانه اتصال نمیده و کار نمیکنه
حتی یک بار دیگه تمام موارد آپدیت رو از داخل برنامه تیک زدم و به روزرسانی کردم. بازم کار نکرد
فعلا ورژن 6.37 هستش که برام کار میکنه
در ضمن برنامه هایی که توی ریلیز قرار داده بودن رو هم تست کردم
اونا هم جواب نداد و کار نکرد

**Comment by lowercase78** [comment]
سلام
این نسخه نیاز به نصب نداره، نسخه هایی که از قبل داشتین رو ببندین ونسخه دانلود شده رو بعد از اکسترکت اجرا کنید .

پنج تا سرور بصورت پیش فرض داره نرم افزار روشون راست کلیک کنید و  Test Server real delay رو بزنید ببینید پینگ میده یا نه، دقت کنید اگه پیام فایروال اومد باید دسترسی اتصال به نرم افزار بدین

**Comment by aghajani82** [comment]
دقیقا همین کار رو کردم.
کانفینگ های شما و مال خودم رو هم تست کردم
پینگ میده. ولی نمیدونم چرا کار نمیکنه.
روی ورژن 6.37 وی تو ری اوکی هستش. ولی از اون ورژن بالاتر نمیدونم چی اضافه شده که برای من اتصال نمیده و کار نمیکنه

**Comment by lowercase78** [comment]
چطور بهش وصل میشین؟

پراکسی مود رو روشن میکنید یا توی تنظیمات پراکسی رو فعال می‌کنید ؟


برای حالت tun یا همون وی‌پی‌ان باید run as admin کنید و حتما توی تنظیمات تیک فرگمنت رو خاموش کنید

**Comment by aghajani82** [comment]
برای اتصال کانفینگ رو انتخاب میکنم
و از طریق سیستم پروکسی اونو روی ست سیستم پروکسی میزارم
روتینگ رو هم گلوبال و یا وایت لیست میزارم
البته همه موارد رو برای اتصال تست کردم
گزینه فرگمنت رو هم خاموش کردم توی تنظیمات
بازم جواب نداد

**Comment by lowercase78** [comment]
نسخه جدید رو تست کنید ، فایل رو روی دسکتاپ اکسترکت و تست کنید ..

**Comment by lowercase78** [comment]
ساعت و تاریخ سیستمتون درسته؟

**Comment by aghajani82** [comment]
تاریخ و ساعت لپ تاپ م درسته.
من الان با سیستم خونه برنامه چک کردم.
هیچ مشکلی نداره. بدون هیچ دستکاری توی تنظیمات برنامه اجرا شد و به خوبی و باسرعت بالا کار کرد. احتمال میدم برنامه های جانبی ویندوزم باید به روزرسانی بشه.
مثل ران تایم و ویژوال های ورژن جدید.
من سیستم خونه رو چون باهاش بازی کامپیوتری میکنم ،از لحاظ مکمل ها کامل هستش. با به روزرسانی احتمال میدم درست بشه. البته ویندوز خونه ۱۰ هستش و لپ تاپ م ویندوز ۷

**Comment by aghajani82** [comment]
![New Picture (3)](https://github.com/lowercase78/V2RayN-PRO/assets/38226451/6e03267b-306a-4631-ab16-42beb4318ce1)
سلام
کارهای قبلی رو انجام دادم
بازم نشد
عکس پیوست شده رو یه نگاهی بندازید
یه پیغام توی کادر سفید رنگ اون پایین هست
مثل حالت ارور ه
یه جورایی وقتی اتصال نمیده اون ارور میاد
وگرنه توی ورژن های پایین تر این ارور رو ندارم
اگر هم مشکل ش مشخص نیست مزاحمتون نمیشم
در کل بیخیالش بشید

**Comment by lowercase78** [comment]
میتونید بقیه کانفیگ‌ها رو تست کنید؟
ممکنه کانفیگی که استفاده کردین ایراد داشته باشه

**Comment by aghajani82** [comment]
راستش کانفینگ خودم در حال حاضر هم روی سیستم و هم روی موبایل داره کار میکنه
روی موبایل که آخرین ورژن وی تو ری ان هستش
روی سیستم هم 6.37 بالاتر کار نمیکنه
وگرنه روی ورژن 6.37 خوبه. موردی نداره
از بابت کانفینگ موردی نیست. احتمالا روی ویندوز 7 بیشتر از این ورژن جواب نمیده
