### ISSUE TITLE
希望能够添加中文界面

### ISSUE THREAD

**Issue by skyhx** [lowercase78/V2RayN-PRO#10]
希望能够添加中文界面

**Comment by DIDIAO2023** [comment]
你只需要点击最顶上一栏最后一个选项“close”右边的三个点，点开第五行的：language“右侧横线上的三角，选择”zh-Hans“，最后关闭v2rayn pro并重启，软件就会变成简体中文界面。

**Comment by skyhx** [comment]
> 你只需要点击最顶上一栏最后一个选项“close”右边的三个点，点开第五行的：language“右侧横线上的三角，选择”zh-Hans“，最后关闭v2rayn pro并重启，软件就会变成简体中文界面。

好的，感谢你的指导，谢谢
