### ISSUE TITLE
v2rayng

### ISSUE THREAD

**Issue by Johnwick-68** [lowercase78/V2RayN-PRO#11]
سلام
برای نسخه اصلاح شده ویندوز بسیار تشکر میکنم عالی هست.خدا قوت
خواستم ببینم برای اندروید و نسخه v2rayng هم میتونید نسخه اصلاح شده برای ایران مثل همین ویندوز رو قرار بدید؟
از نسخه مهسا انجی استفاده میکنم اما نیازمند نسخه جدید V2rayng هستم که اصلاح شده باشه

با تشکر از شما

**Comment by lowercase78** [comment]
خوشحالم که تلاشم مفید بوده،

یه مورد رو باید عرض کنم ماهیت نسخه اندروید با ویندوز فرق داره و نسخه اندروید اصلا هسته سینگ باکس رو ساپورت نمیکنه..

در مورد هسته ایکس‌ری، اپلیکیشین مهسا ان‌جی توسط خود ناکر توسعه داده شده و آخرین نسخه از هسته رو اضافه کردن
