### ISSUE TITLE
stop کردن کانفیگ

### ISSUE THREAD

**Issue by Alij13a** [lowercase78/V2RayN-PRO#13]
سلام
چرا داخل v2rayn pro مثل nekoray دکمه ای برای استوپ کردن کانفیگ نداره؟
داخل nekorey وقتی ctrl + s رو بزنیم کانفیگ استوپ میشه ولی داخل v2rayn pro همچین چیزی نتونستم پیدا کنم.

لطفا راهنمایی کنید.

باتشکر

**Comment by lowercase78** [comment]
نرم افزار اصلی رو 2dust نوشته و من فقط کانفیگ رو برای ایران تنطیم کردم ، در صورت نیاز به اضافه کردن امکانات جدید باید توی رپوی اصلی درخواست بزنید ..

**Comment by Alij13a** [comment]
> نرم افزار اصلی رو 2dust نوشته و من فقط کانفیگ رو برای ایران تنطیم کردم ، در صورت نیاز به اضافه کردن امکانات جدید باید توی رپوی اصلی درخواست بزنید ..

منظورم این نیست که قابلیت جدید اضافه کنید فقط میخام اگر اطلاع دارید چطوریه به منم بگید.
