### ISSUE TITLE
TUN mode

### ISSUE THREAD

**Issue by saeed3322** [lowercase78/V2RayN-PRO#14]
روتینگی که نوشتید واسه مستقیم کردن سایت های ایرانی در حالت TUN mode کار نمیکنه . 
اکثر اوقات نیاز هست که کل سیستم عامل رو بندازیم پشت پروکسی که نیاز به استفاده از TUN mode  هست.

**Comment by lowercase78** [comment]
با کانفیگ های وارپ تست شده ، فایل geoip  رو هم اد کردم که مشکلی نداشته باشه ، با نسخه آخر تست کنید ..
