### ISSUE TITLE
اصلاح قوانین مسیریابی کاستوم

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [lowercase78/V2RayN-PRO#16]
سلام و با تشکر از زحمات خوبتون.

یک نکته ای رو درباره قوانین مسیریابی مخصوص ایران که در این بسته قرار دادید دیدم و میخواستم اینجا متذکر بشم.

![____2024_07_31_03_49_20_RoutingRuleDetailsSetting](https://github.com/user-attachments/assets/48da455f-05dc-4cfe-8af4-6864ce09b215)

قوانینی که در قسمت زرد وجود دارن و با کاما از هم جدا شدن با هم OR میشن (بطور کلی بین قوانین یک ستون همیشه OR اعمال میشه).  ولی بین مجموعه این قوانین و قوانین ستونهای دیگه مثل ستون قرمز AND صورت میگیره (یعنی قانون فقط وقتی اعمال میشه که هر دو شرط در هر دو ستون محقق بشه). 

به این صورت فعلی که در نرم افزار هست و در بالا اومده، اون قانون روتینگ مستقیم فقط وقتی اعمال میشه که هم دامین و هم آیپی هر دو مچ بشن که شاید مد نظر نباشه و در خیلی از موارد این شرطها همزمان برآورده نمیشن و در نتیجه باعث میشه سایت ایرانی باز هم از پراکسی رد بشه.

به همین دلیل مناسب تره که قوانین بر پایه IP و دامین از هم جدا بشه و در قوانین جداگانه قرار بگیره (حداقل دو تا قانون direct).

با تشکر

**Comment by TheLordOfTheKings** [comment]
@OnceUponATimeInAmerica
اگه قرار باشه دوتا رول بشن، برای سایت های داخلی باید همش سوئیچ کرد بین این دوتا؟ اینجوری خیلی سخت میشه که.
میشه جور دیگه ای این رول ها or بشن؟

**Comment by lowercase78** [comment]
سلام دوست عزیز ، ممنون از توجهت

اگه پوشه v2rayN رو باز کنید و به مسیر زیر برین 

v2rayN-Pro => guiConfigs => config.json

میتونید فایل کانفیگ نهایی که با هسته اجرا میشه رو ببینید ، قوانین مسیریابی به شکل زیر هست :

`  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "outboundTag": "block",
        "ip": [
          "10.10.34.34",
          "10.10.34.35",
          "10.10.34.36"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:private"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:private"
        ]
      },
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads-all"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:category-ir",
          "domain:ir"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:ir"
        ]
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy"
      }
    ]
  }`
  
  اگه بازم فکر میکنید مشکل هست بگین تا با هم اصلاحش کنیم ..
