### ISSUE TITLE
فرگمنت 

### ISSUE THREAD

**Issue by MasoudBJ** [lowercase78/V2RayN-PRO#17]
سلام، من از اینترنت های وب استفاده میکنم، متاسفانه فرگمنت روی این اینترنت کار نمیکنه، تنظیماتی هست که با انجامش فرگمنت کار کنه؟

**Comment by arp7vpn** [comment]
با اسکنر فرگمنت خودتون می تونین اسکن کنین و مقادیر بهینه رو پیدا کنین.

**Comment by lowercase78** [comment]
هسته مورد استفاده خاصیت تنظیم اتوماتیک فرگمنت رو داره،

پیش اومده کانفیگ تایم اوت بزنه ولی اگه انتخابش کنید وصل بشه، تست بفرمایید
