### ISSUE TITLE
انتقال تنظیمات به اندروید

### ISSUE THREAD

**Issue by farzad-prime** [lowercase78/V2RayN-PRO#19]
سلام با تشکر از زحمات
آیا امکانش هست تنظیماتی که در این ورژن اعمال شده به یک نرم افزار اندروید با ساپورت sing box مثل nekoox / husi / karing انتقال داد؟
کانفیگ hysteria 2 روی این نرم افزار عالی کار میکنه ولی روی اندروید نه

**Comment by lowercase78** [comment]
نرم‌افزار مهسا‌ ان‌جی یا نیکا‌ان ان جی رو تست کنید،
چون هسته‌ها یکسان هستن احتمال زیاد جواب بده
