### ISSUE TITLE
تداخل فرگمنت و تون مود

### ISSUE THREAD

**Issue by JWick90** [lowercase78/V2RayN-PRO#2]
سلام. یه مشکلی هست که ورژن عادی v2rayn هم بوده ولی گفتم اینجا بپرسم بهتره
ممکنه فرگمنت روشن رو با تون مود همزمان استفاده کنید ببینید چطوره ؟
من هرموقع فرگمنت روشنه ، تون مود رو روشن میکنم دیگه کلا از کار میافته اتصال!
رو حالت فرگمنت خاموش مشکلی نداره! عجیبه...

**Comment by lowercase78** [comment]
این مشکل مربوط به v2rayN هست که خودشون هم توی توضیحات نوشتن کهاختلال داره فرگمنت با tun

باید منتظر شد ببینیم دولوپر مشکل رو رفع میکنن..

**Comment by lowercase78** [comment]
این مورد رو مجددا تست کردم ، علتش اینه که نرم افزار کانفیگ رو با هسته سینگ باکس اجرا میکنه و به همین دلیل فرگمنت از کار میفته ..
