### ISSUE TITLE
When will the macOS version client be online?

### ISSUE THREAD

**Issue by Skylush** [lowercase78/V2RayN-PRO#21]
Urgent need for macOS client V2RayN-PRO

**Comment by lowercase78** [comment]
This application is based on the 2dust\v2rayN and orginal one doesn't support Mac os

**Comment by hosseinc** [comment]
actually it does. https://github.com/2dust/v2rayN/releases/download/7.17.3/v2rayN-macos-arm64.dmg

@lowercase78
