### ISSUE TITLE
راهی هست که از این تغییرات مستقیم تو پنل استفاده کرد؟

### ISSUE THREAD

**Issue by aboozar1368** [lowercase78/V2RayN-PRO#3]
سلام اگه این تغییراتی که در هسته xray دادین و سایر تغییراتی که داره رو بخوایم داخل پنل ها استفاده کنیم چکاری باید انجام داد اصلا این کارو میشه کرد یا خیر

**Comment by lowercase78** [comment]
هسته ایکس‌ری رو میتونید از گیت هاب ناکر دانلود کنید ولی عملا داخل ایران بدرد میخوره،

اگه تانل میزنید شاید با تغییر هسته بتونید ازش بهره ببرید

**Comment by aboozar1368** [comment]
ممنونم ازتون
