### ISSUE TITLE
Failed to run Core, please see the log ارور 

### ISSUE THREAD

**Issue by nadergithub** [lowercase78/V2RayN-PRO#4]
وقت بخیر وقتی ctl+eرو میزنم که پینگ و سرعت بگیرم این خطا رو میده Failed to run Core, please see the log

**Comment by seed4me01** [comment]
درود
برای من هم همینطور هست 
و همچنین 
وقتی TuN را فعال میکنم پینگ ۱- میشه و دیتا رد و بدل نمیشه .

**Comment by lowercase78** [comment]
لطفا نسخه جدید رو تست کنید ، روی سیستم خودم تست کردم مشکلی نداره ..

حدسم اینه به خاطر dns باشه .
