### ISSUE TITLE
virustotal.com Warning

### ISSUE THREAD

**Issue by amirhoseinsadeghi** [lowercase78/V2RayN-PRO#6]
why?
![2024-06-24_121302](https://github.com/lowercase78/V2RayN-PRO/assets/106965411/8ddd9d85-f43d-4fd9-8217-b1a5ffa3ac2b)

**Comment by lowercase78** [comment]
توضیح دادم، به خاطر سیگنچر هست، جهت اطمینان بیشتر میتونید فایلهای کانفیگ رو دریافت و خودتون جایگزین کنید.
