### ISSUE TITLE
Backdoor???????

### ISSUE THREAD

**Issue by PersiaNDreameR** [lowercase78/V2RayN-PRO#7]
what is issue of virus total please fastly explain it for all of us

**Comment by lowercase78** [comment]
پیشنهاد میدم از نسخه اصلی وی توی ری و کانفیگ ‌ها استفاده کنید یا از نسخه های غیر از pre ،

توضیح دادم چون سیگنچر ندارم ممکنه بیلد من رو خطا بده..

به هر حال خطای گرفته شده به علت کد نیست.
