### ISSUE TITLE
Please add the license.

### ISSUE THREAD

**Issue by T1anjiu** [lowercase78/V2RayN-PRO#8]
As a open-source worker, you should understand the role of open source licenses，and its importance.I hope you can add the original GPL 3.0 license

**Comment by lowercase78** [comment]
Done 🙏

**Comment by Crowbar9319** [comment]
The GNU General Public License version 3 (GPL-3.0) is a widely used free software license. Here are some key points about GPL-3.0:

1. Freedom: It grants users the freedom to run, study, share, and modify the software.

2. Copyleft: It requires that any derivative works or modifications must also be distributed under the same license terms.

3. Patent rights: It includes an express grant of patent rights from contributors to users.

4. Compatibility: It's compatible with many other open source licenses, but not all.

5. Source code provision: Distributors must make the source code available to recipients.

6. Installation information: For consumer products, it requires providing installation information.

7. DRM: It has provisions to prevent DRM from restricting users' freedom.

8. Tivoization: It includes clauses to prevent "tivoization" (hardware restrictions on modified versions).

9. Termination: License termination occurs if you violate the terms, but can be reinstated.

10. No warranty: Like most open source licenses, it comes with no warranty.

Using GPL-3.0 for your software means:
- Anyone can use, modify, and distribute your code.
- They must provide source code for any modifications.
- Any software that incorporates your code must also be licensed under GPL-3.0.

It's a strong copyleft license that ensures software freedom, but it may not be suitable for all projects, especially if you want to allow proprietary use of your code. Always consult with a legal professional when choosing a license for your software.

**Comment by T1anjiu** [comment]
> The GNU General Public License version 3 (GPL-3.0) :
> 
> 
> 
> **1. Copyleft: It requires that any derivative works or modifications must also be distributed under the same license terms.**
> 
> 
> **2. Source code provision: Distributors must make the source code available to recipients.**
> 
> 
> 
> **3. Tivoization: It includes clauses to prevent "tivoization" (hardware restrictions on modified versions).**
> 
> 
> 
> 

Yes, the source project V2rayN uses GPL-3.0

**Comment by lowercase78** [comment]
i have add a link to [source project](https://github.com/2dust/v2rayN/releases) V2rayN in Readme :

https://github.com/lowercase78/V2RayN-PRO/blob/main/README_EN.md
