### ISSUE TITLE
EOF error - ارور

### ISSUE THREAD

**Issue by Alij13a** [lowercase78/V2RayN-PRO#9]
سلام
موقع اتصال ارور eof میده.
هر 4 تا روتینگ رو امتحان کردم و فرقی نکرد.
فرگمنت رو هم رو خاموش گذاشتم و تست کردم باز هم فرقی نکرد.
برنامه رو حالت ادمین هم ران کردم فرقی نکرد.

مشکل چیه و چطور میشه حل کرد؟

<img width="887" alt="Screenshot 2024-06-25 17410312" src="https://github.com/lowercase78/V2RayN-PRO/assets/160029684/8e6ad577-cc23-4d68-bb91-fab5fcdfcb77">

فقط در حالتی وصل میشه که tun خاموش باشه که وقتی هم خاموشه برنامه های روی سیستم از Vpn عبور داده نمی شود.

مشکل چیه و چطور میشه حل کرد؟

**Comment by lowercase78** [comment]
کانفیگ‌های وارپ رو هم تست کردین؟

مشکل اینجاست که کانفیگی که شما دارین تست می‌کنید تو حالت tun به سینگ‌باکس تبدیل میشه و حدس می‌زنم چون دامنه مورد استفاده فیلتره نمیتونه کانکت بشه..

**Comment by Alij13a** [comment]
با همون کانفیگ و روی حالت tun روی نکو ری میتونم وصل بشم.
داخل کانفیگ ادیت هم رفتم به  xray تغییر دادم ولی فرقی نکرد
چیزی هم فیلتر نیست توی کانفیگ.

**Comment by lowercase78** [comment]
چک کنید ببینید داخل پوشه bin فایل geoip-ir.srs وجود داره؟

اگه نیست، دانلود و جایگزینش کنید.
